//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicimaxWebServicesSample.UyeServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UyeGirisi", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UyeGirisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Admin {
            get {
                return this.AdminField;
            }
            set {
                if ((this.AdminField.Equals(value) != true)) {
                    this.AdminField = value;
                    this.RaisePropertyChanged("Admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Otp {
            get {
                return this.OtpField;
            }
            set {
                if ((object.ReferenceEquals(this.OtpField, value) != true)) {
                    this.OtpField = value;
                    this.RaisePropertyChanged("Otp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UyeGirisiSonuc", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UyeGirisiSonuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BasariliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KullaniciIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OtpZorunluField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> RollerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SifreSifirlaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Basarili {
            get {
                return this.BasariliField;
            }
            set {
                if ((this.BasariliField.Equals(value) != true)) {
                    this.BasariliField = value;
                    this.RaisePropertyChanged("Basarili");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Isim {
            get {
                return this.IsimField;
            }
            set {
                if ((object.ReferenceEquals(this.IsimField, value) != true)) {
                    this.IsimField = value;
                    this.RaisePropertyChanged("Isim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KullaniciID {
            get {
                return this.KullaniciIDField;
            }
            set {
                if ((this.KullaniciIDField.Equals(value) != true)) {
                    this.KullaniciIDField = value;
                    this.RaisePropertyChanged("KullaniciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OtpZorunlu {
            get {
                return this.OtpZorunluField;
            }
            set {
                if ((this.OtpZorunluField.Equals(value) != true)) {
                    this.OtpZorunluField = value;
                    this.RaisePropertyChanged("OtpZorunlu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Roller {
            get {
                return this.RollerField;
            }
            set {
                if ((object.ReferenceEquals(this.RollerField, value) != true)) {
                    this.RollerField = value;
                    this.RaisePropertyChanged("Roller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SifreSifirla {
            get {
                return this.SifreSifirlaField;
            }
            set {
                if ((this.SifreSifirlaField.Equals(value) != true)) {
                    this.SifreSifirlaField = value;
                    this.RaisePropertyChanged("SifreSifirla");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UyeFiltre", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UyeFiltre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AktifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlisverisYaptiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CinsiyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DogumTarihi1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DogumTarihi2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DuzenlemeTarihi1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DuzenlemeTarihi2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IlIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IlceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MailIzinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MusteriKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SmsIzinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SonGirisTarihi1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SonGirisTarihi2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UyeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UyelikTarihi1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UyelikTarihi2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Aktif {
            get {
                return this.AktifField;
            }
            set {
                if ((this.AktifField.Equals(value) != true)) {
                    this.AktifField = value;
                    this.RaisePropertyChanged("Aktif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlisverisYapti {
            get {
                return this.AlisverisYaptiField;
            }
            set {
                if ((this.AlisverisYaptiField.Equals(value) != true)) {
                    this.AlisverisYaptiField = value;
                    this.RaisePropertyChanged("AlisverisYapti");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cinsiyet {
            get {
                return this.CinsiyetField;
            }
            set {
                if ((this.CinsiyetField.Equals(value) != true)) {
                    this.CinsiyetField = value;
                    this.RaisePropertyChanged("Cinsiyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DogumTarihi1 {
            get {
                return this.DogumTarihi1Field;
            }
            set {
                if ((this.DogumTarihi1Field.Equals(value) != true)) {
                    this.DogumTarihi1Field = value;
                    this.RaisePropertyChanged("DogumTarihi1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DogumTarihi2 {
            get {
                return this.DogumTarihi2Field;
            }
            set {
                if ((this.DogumTarihi2Field.Equals(value) != true)) {
                    this.DogumTarihi2Field = value;
                    this.RaisePropertyChanged("DogumTarihi2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DuzenlemeTarihi1 {
            get {
                return this.DuzenlemeTarihi1Field;
            }
            set {
                if ((this.DuzenlemeTarihi1Field.Equals(value) != true)) {
                    this.DuzenlemeTarihi1Field = value;
                    this.RaisePropertyChanged("DuzenlemeTarihi1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DuzenlemeTarihi2 {
            get {
                return this.DuzenlemeTarihi2Field;
            }
            set {
                if ((this.DuzenlemeTarihi2Field.Equals(value) != true)) {
                    this.DuzenlemeTarihi2Field = value;
                    this.RaisePropertyChanged("DuzenlemeTarihi2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlID {
            get {
                return this.IlIDField;
            }
            set {
                if ((this.IlIDField.Equals(value) != true)) {
                    this.IlIDField = value;
                    this.RaisePropertyChanged("IlID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlceID {
            get {
                return this.IlceIDField;
            }
            set {
                if ((this.IlceIDField.Equals(value) != true)) {
                    this.IlceIDField = value;
                    this.RaisePropertyChanged("IlceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MailIzin {
            get {
                return this.MailIzinField;
            }
            set {
                if ((this.MailIzinField.Equals(value) != true)) {
                    this.MailIzinField = value;
                    this.RaisePropertyChanged("MailIzin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MusteriKodu {
            get {
                return this.MusteriKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.MusteriKoduField, value) != true)) {
                    this.MusteriKoduField = value;
                    this.RaisePropertyChanged("MusteriKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SmsIzin {
            get {
                return this.SmsIzinField;
            }
            set {
                if ((this.SmsIzinField.Equals(value) != true)) {
                    this.SmsIzinField = value;
                    this.RaisePropertyChanged("SmsIzin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SonGirisTarihi1 {
            get {
                return this.SonGirisTarihi1Field;
            }
            set {
                if ((this.SonGirisTarihi1Field.Equals(value) != true)) {
                    this.SonGirisTarihi1Field = value;
                    this.RaisePropertyChanged("SonGirisTarihi1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SonGirisTarihi2 {
            get {
                return this.SonGirisTarihi2Field;
            }
            set {
                if ((this.SonGirisTarihi2Field.Equals(value) != true)) {
                    this.SonGirisTarihi2Field = value;
                    this.RaisePropertyChanged("SonGirisTarihi2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UyeID {
            get {
                return this.UyeIDField;
            }
            set {
                if ((this.UyeIDField.Equals(value) != true)) {
                    this.UyeIDField = value;
                    this.RaisePropertyChanged("UyeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UyelikTarihi1 {
            get {
                return this.UyelikTarihi1Field;
            }
            set {
                if ((this.UyelikTarihi1Field.Equals(value) != true)) {
                    this.UyelikTarihi1Field = value;
                    this.RaisePropertyChanged("UyelikTarihi1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UyelikTarihi2 {
            get {
                return this.UyelikTarihi2Field;
            }
            set {
                if ((this.UyelikTarihi2Field.Equals(value) != true)) {
                    this.UyelikTarihi2Field = value;
                    this.RaisePropertyChanged("UyelikTarihi2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UyeSayfalama", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UyeSayfalama : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KayitSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SayfaNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiralamaDegeriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiralamaYonuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KayitSayisi {
            get {
                return this.KayitSayisiField;
            }
            set {
                if ((this.KayitSayisiField.Equals(value) != true)) {
                    this.KayitSayisiField = value;
                    this.RaisePropertyChanged("KayitSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SayfaNo {
            get {
                return this.SayfaNoField;
            }
            set {
                if ((this.SayfaNoField.Equals(value) != true)) {
                    this.SayfaNoField = value;
                    this.RaisePropertyChanged("SayfaNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiralamaDegeri {
            get {
                return this.SiralamaDegeriField;
            }
            set {
                if ((object.ReferenceEquals(this.SiralamaDegeriField, value) != true)) {
                    this.SiralamaDegeriField = value;
                    this.RaisePropertyChanged("SiralamaDegeri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiralamaYonu {
            get {
                return this.SiralamaYonuField;
            }
            set {
                if ((object.ReferenceEquals(this.SiralamaYonuField, value) != true)) {
                    this.SiralamaYonuField = value;
                    this.RaisePropertyChanged("SiralamaYonu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Uye", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Uye : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CepTelefonuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CinsiyetIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DogumTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DuzenlemeTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IlIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IlceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double KrediLimitiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MailIzinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeslekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MusteriKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OgrenimDurumuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParaPuanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SmsIzinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SonGirisTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyisimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UyeTuruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UyeTuruIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UyelikTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UyelikTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UyelikTipiIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CepTelefonu {
            get {
                return this.CepTelefonuField;
            }
            set {
                if ((object.ReferenceEquals(this.CepTelefonuField, value) != true)) {
                    this.CepTelefonuField = value;
                    this.RaisePropertyChanged("CepTelefonu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CinsiyetID {
            get {
                return this.CinsiyetIDField;
            }
            set {
                if ((this.CinsiyetIDField.Equals(value) != true)) {
                    this.CinsiyetIDField = value;
                    this.RaisePropertyChanged("CinsiyetID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DogumTarihi {
            get {
                return this.DogumTarihiField;
            }
            set {
                if ((this.DogumTarihiField.Equals(value) != true)) {
                    this.DogumTarihiField = value;
                    this.RaisePropertyChanged("DogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DuzenlemeTarihi {
            get {
                return this.DuzenlemeTarihiField;
            }
            set {
                if ((this.DuzenlemeTarihiField.Equals(value) != true)) {
                    this.DuzenlemeTarihiField = value;
                    this.RaisePropertyChanged("DuzenlemeTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Il {
            get {
                return this.IlField;
            }
            set {
                if ((object.ReferenceEquals(this.IlField, value) != true)) {
                    this.IlField = value;
                    this.RaisePropertyChanged("Il");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlID {
            get {
                return this.IlIDField;
            }
            set {
                if ((this.IlIDField.Equals(value) != true)) {
                    this.IlIDField = value;
                    this.RaisePropertyChanged("IlID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ilce {
            get {
                return this.IlceField;
            }
            set {
                if ((object.ReferenceEquals(this.IlceField, value) != true)) {
                    this.IlceField = value;
                    this.RaisePropertyChanged("Ilce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlceID {
            get {
                return this.IlceIDField;
            }
            set {
                if ((this.IlceIDField.Equals(value) != true)) {
                    this.IlceIDField = value;
                    this.RaisePropertyChanged("IlceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Isim {
            get {
                return this.IsimField;
            }
            set {
                if ((object.ReferenceEquals(this.IsimField, value) != true)) {
                    this.IsimField = value;
                    this.RaisePropertyChanged("Isim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double KrediLimiti {
            get {
                return this.KrediLimitiField;
            }
            set {
                if ((this.KrediLimitiField.Equals(value) != true)) {
                    this.KrediLimitiField = value;
                    this.RaisePropertyChanged("KrediLimiti");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MailIzin {
            get {
                return this.MailIzinField;
            }
            set {
                if ((this.MailIzinField.Equals(value) != true)) {
                    this.MailIzinField = value;
                    this.RaisePropertyChanged("MailIzin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Meslek {
            get {
                return this.MeslekField;
            }
            set {
                if ((object.ReferenceEquals(this.MeslekField, value) != true)) {
                    this.MeslekField = value;
                    this.RaisePropertyChanged("Meslek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MusteriKodu {
            get {
                return this.MusteriKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.MusteriKoduField, value) != true)) {
                    this.MusteriKoduField = value;
                    this.RaisePropertyChanged("MusteriKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OgrenimDurumu {
            get {
                return this.OgrenimDurumuField;
            }
            set {
                if ((object.ReferenceEquals(this.OgrenimDurumuField, value) != true)) {
                    this.OgrenimDurumuField = value;
                    this.RaisePropertyChanged("OgrenimDurumu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParaPuan {
            get {
                return this.ParaPuanField;
            }
            set {
                if ((this.ParaPuanField.Equals(value) != true)) {
                    this.ParaPuanField = value;
                    this.RaisePropertyChanged("ParaPuan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SmsIzin {
            get {
                return this.SmsIzinField;
            }
            set {
                if ((this.SmsIzinField.Equals(value) != true)) {
                    this.SmsIzinField = value;
                    this.RaisePropertyChanged("SmsIzin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SonGirisTarihi {
            get {
                return this.SonGirisTarihiField;
            }
            set {
                if ((this.SonGirisTarihiField.Equals(value) != true)) {
                    this.SonGirisTarihiField = value;
                    this.RaisePropertyChanged("SonGirisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyisim {
            get {
                return this.SoyisimField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyisimField, value) != true)) {
                    this.SoyisimField = value;
                    this.RaisePropertyChanged("Soyisim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UyeTuru {
            get {
                return this.UyeTuruField;
            }
            set {
                if ((object.ReferenceEquals(this.UyeTuruField, value) != true)) {
                    this.UyeTuruField = value;
                    this.RaisePropertyChanged("UyeTuru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UyeTuruID {
            get {
                return this.UyeTuruIDField;
            }
            set {
                if ((this.UyeTuruIDField.Equals(value) != true)) {
                    this.UyeTuruIDField = value;
                    this.RaisePropertyChanged("UyeTuruID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UyelikTarihi {
            get {
                return this.UyelikTarihiField;
            }
            set {
                if ((this.UyelikTarihiField.Equals(value) != true)) {
                    this.UyelikTarihiField = value;
                    this.RaisePropertyChanged("UyelikTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UyelikTipi {
            get {
                return this.UyelikTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.UyelikTipiField, value) != true)) {
                    this.UyelikTipiField = value;
                    this.RaisePropertyChanged("UyelikTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UyelikTipiID {
            get {
                return this.UyelikTipiIDField;
            }
            set {
                if ((this.UyelikTipiIDField.Equals(value) != true)) {
                    this.UyelikTipiIDField = value;
                    this.RaisePropertyChanged("UyelikTipiID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UyeAyar", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UyeAyar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CepTelefonuGuncelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CinsiyetGuncelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DogumTarihiGuncelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IlGuncelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IlceGuncelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsimGuncelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool KrediLimitiGuncelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MailGuncelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MailIzinGuncelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MeslekGuncelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MusteriKoduGuncelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SifreGuncelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<TicimaxWebServicesSample.UyeServis.UyeSifreKaydetmeTuru> SifreKaydetmeTuruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SmsIzinGuncelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TelefonGuncelleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UyelikTarihiGuncelleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CepTelefonuGuncelle {
            get {
                return this.CepTelefonuGuncelleField;
            }
            set {
                if ((this.CepTelefonuGuncelleField.Equals(value) != true)) {
                    this.CepTelefonuGuncelleField = value;
                    this.RaisePropertyChanged("CepTelefonuGuncelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CinsiyetGuncelle {
            get {
                return this.CinsiyetGuncelleField;
            }
            set {
                if ((this.CinsiyetGuncelleField.Equals(value) != true)) {
                    this.CinsiyetGuncelleField = value;
                    this.RaisePropertyChanged("CinsiyetGuncelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DogumTarihiGuncelle {
            get {
                return this.DogumTarihiGuncelleField;
            }
            set {
                if ((this.DogumTarihiGuncelleField.Equals(value) != true)) {
                    this.DogumTarihiGuncelleField = value;
                    this.RaisePropertyChanged("DogumTarihiGuncelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IlGuncelle {
            get {
                return this.IlGuncelleField;
            }
            set {
                if ((this.IlGuncelleField.Equals(value) != true)) {
                    this.IlGuncelleField = value;
                    this.RaisePropertyChanged("IlGuncelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IlceGuncelle {
            get {
                return this.IlceGuncelleField;
            }
            set {
                if ((this.IlceGuncelleField.Equals(value) != true)) {
                    this.IlceGuncelleField = value;
                    this.RaisePropertyChanged("IlceGuncelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsimGuncelle {
            get {
                return this.IsimGuncelleField;
            }
            set {
                if ((this.IsimGuncelleField.Equals(value) != true)) {
                    this.IsimGuncelleField = value;
                    this.RaisePropertyChanged("IsimGuncelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool KrediLimitiGuncelle {
            get {
                return this.KrediLimitiGuncelleField;
            }
            set {
                if ((this.KrediLimitiGuncelleField.Equals(value) != true)) {
                    this.KrediLimitiGuncelleField = value;
                    this.RaisePropertyChanged("KrediLimitiGuncelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MailGuncelle {
            get {
                return this.MailGuncelleField;
            }
            set {
                if ((this.MailGuncelleField.Equals(value) != true)) {
                    this.MailGuncelleField = value;
                    this.RaisePropertyChanged("MailGuncelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MailIzinGuncelle {
            get {
                return this.MailIzinGuncelleField;
            }
            set {
                if ((this.MailIzinGuncelleField.Equals(value) != true)) {
                    this.MailIzinGuncelleField = value;
                    this.RaisePropertyChanged("MailIzinGuncelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MeslekGuncelle {
            get {
                return this.MeslekGuncelleField;
            }
            set {
                if ((this.MeslekGuncelleField.Equals(value) != true)) {
                    this.MeslekGuncelleField = value;
                    this.RaisePropertyChanged("MeslekGuncelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MusteriKoduGuncelle {
            get {
                return this.MusteriKoduGuncelleField;
            }
            set {
                if ((this.MusteriKoduGuncelleField.Equals(value) != true)) {
                    this.MusteriKoduGuncelleField = value;
                    this.RaisePropertyChanged("MusteriKoduGuncelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SifreGuncelle {
            get {
                return this.SifreGuncelleField;
            }
            set {
                if ((this.SifreGuncelleField.Equals(value) != true)) {
                    this.SifreGuncelleField = value;
                    this.RaisePropertyChanged("SifreGuncelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<TicimaxWebServicesSample.UyeServis.UyeSifreKaydetmeTuru> SifreKaydetmeTuru {
            get {
                return this.SifreKaydetmeTuruField;
            }
            set {
                if ((this.SifreKaydetmeTuruField.Equals(value) != true)) {
                    this.SifreKaydetmeTuruField = value;
                    this.RaisePropertyChanged("SifreKaydetmeTuru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SmsIzinGuncelle {
            get {
                return this.SmsIzinGuncelleField;
            }
            set {
                if ((this.SmsIzinGuncelleField.Equals(value) != true)) {
                    this.SmsIzinGuncelleField = value;
                    this.RaisePropertyChanged("SmsIzinGuncelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TelefonGuncelle {
            get {
                return this.TelefonGuncelleField;
            }
            set {
                if ((this.TelefonGuncelleField.Equals(value) != true)) {
                    this.TelefonGuncelleField = value;
                    this.RaisePropertyChanged("TelefonGuncelle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UyelikTarihiGuncelle {
            get {
                return this.UyelikTarihiGuncelleField;
            }
            set {
                if ((this.UyelikTarihiGuncelleField.Equals(value) != true)) {
                    this.UyelikTarihiGuncelleField = value;
                    this.RaisePropertyChanged("UyelikTarihiGuncelle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UyeSifreKaydetmeTuru", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum UyeSifreKaydetmeTuru : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Plain = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hash = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UyeAdres", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UyeAdres : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresTarifiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AktifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliciTelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsKurumsalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostaKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SehirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TanimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UlkeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UyeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VergiDairesiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VergiNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdresTarifi {
            get {
                return this.AdresTarifiField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresTarifiField, value) != true)) {
                    this.AdresTarifiField = value;
                    this.RaisePropertyChanged("AdresTarifi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aktif {
            get {
                return this.AktifField;
            }
            set {
                if ((this.AktifField.Equals(value) != true)) {
                    this.AktifField = value;
                    this.RaisePropertyChanged("Aktif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliciAdi {
            get {
                return this.AliciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AliciAdiField, value) != true)) {
                    this.AliciAdiField = value;
                    this.RaisePropertyChanged("AliciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliciTelefon {
            get {
                return this.AliciTelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.AliciTelefonField, value) != true)) {
                    this.AliciTelefonField = value;
                    this.RaisePropertyChanged("AliciTelefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirmaAdi {
            get {
                return this.FirmaAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaAdiField, value) != true)) {
                    this.FirmaAdiField = value;
                    this.RaisePropertyChanged("FirmaAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ilce {
            get {
                return this.IlceField;
            }
            set {
                if ((object.ReferenceEquals(this.IlceField, value) != true)) {
                    this.IlceField = value;
                    this.RaisePropertyChanged("Ilce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsKurumsal {
            get {
                return this.IsKurumsalField;
            }
            set {
                if ((this.IsKurumsalField.Equals(value) != true)) {
                    this.IsKurumsalField = value;
                    this.RaisePropertyChanged("IsKurumsal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostaKodu {
            get {
                return this.PostaKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.PostaKoduField, value) != true)) {
                    this.PostaKoduField = value;
                    this.RaisePropertyChanged("PostaKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sehir {
            get {
                return this.SehirField;
            }
            set {
                if ((object.ReferenceEquals(this.SehirField, value) != true)) {
                    this.SehirField = value;
                    this.RaisePropertyChanged("Sehir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tanim {
            get {
                return this.TanimField;
            }
            set {
                if ((object.ReferenceEquals(this.TanimField, value) != true)) {
                    this.TanimField = value;
                    this.RaisePropertyChanged("Tanim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ulke {
            get {
                return this.UlkeField;
            }
            set {
                if ((object.ReferenceEquals(this.UlkeField, value) != true)) {
                    this.UlkeField = value;
                    this.RaisePropertyChanged("Ulke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UyeId {
            get {
                return this.UyeIdField;
            }
            set {
                if ((this.UyeIdField.Equals(value) != true)) {
                    this.UyeIdField = value;
                    this.RaisePropertyChanged("UyeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VergiDairesi {
            get {
                return this.VergiDairesiField;
            }
            set {
                if ((object.ReferenceEquals(this.VergiDairesiField, value) != true)) {
                    this.VergiDairesiField = value;
                    this.RaisePropertyChanged("VergiDairesi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VergiNo {
            get {
                return this.VergiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.VergiNoField, value) != true)) {
                    this.VergiNoField = value;
                    this.RaisePropertyChanged("VergiNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UyeTuru", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UyeTuru : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TicimaxWebServicesSample.UyeServis.FiyatTuru FiyatTuruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TanimField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TicimaxWebServicesSample.UyeServis.FiyatTuru FiyatTuru {
            get {
                return this.FiyatTuruField;
            }
            set {
                if ((this.FiyatTuruField.Equals(value) != true)) {
                    this.FiyatTuruField = value;
                    this.RaisePropertyChanged("FiyatTuru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tanim {
            get {
                return this.TanimField;
            }
            set {
                if ((object.ReferenceEquals(this.TanimField, value) != true)) {
                    this.TanimField = value;
                    this.RaisePropertyChanged("Tanim");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FiyatTuru", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum FiyatTuru : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SatisFiyati = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UyeTipiFiyati1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UyeTipiFiyati2 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UyeTipiFiyati3 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UyeTipiFiyati4 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UyeTipiFiyati5 = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServisResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TicimaxWebServicesSample.UyeServis.UyeIzinGecmisiResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TicimaxWebServicesSample.UyeServis.UyeSilResponse))]
    public partial class WebServisResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UyeIzinGecmisiResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UyeIzinGecmisiResponse : TicimaxWebServicesSample.UyeServis.WebServisResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<TicimaxWebServicesSample.UyeServis.UyeIzinGecmisi> IzinGecmisiListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TicimaxWebServicesSample.UyeServis.UyeIzinGecmisi> IzinGecmisiList {
            get {
                return this.IzinGecmisiListField;
            }
            set {
                if ((object.ReferenceEquals(this.IzinGecmisiListField, value) != true)) {
                    this.IzinGecmisiListField = value;
                    this.RaisePropertyChanged("IzinGecmisiList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UyeSilResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UyeSilResponse : TicimaxWebServicesSample.UyeServis.WebServisResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UyeIzinGecmisi", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UyeIzinGecmisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DegerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Duzenleyen_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IzinTipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KaynakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UyeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deger {
            get {
                return this.DegerField;
            }
            set {
                if ((this.DegerField.Equals(value) != true)) {
                    this.DegerField = value;
                    this.RaisePropertyChanged("Deger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duzenleyen_Id {
            get {
                return this.Duzenleyen_IdField;
            }
            set {
                if ((this.Duzenleyen_IdField.Equals(value) != true)) {
                    this.Duzenleyen_IdField = value;
                    this.RaisePropertyChanged("Duzenleyen_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IzinTip {
            get {
                return this.IzinTipField;
            }
            set {
                if ((this.IzinTipField.Equals(value) != true)) {
                    this.IzinTipField = value;
                    this.RaisePropertyChanged("IzinTip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kaynak {
            get {
                return this.KaynakField;
            }
            set {
                if ((object.ReferenceEquals(this.KaynakField, value) != true)) {
                    this.KaynakField = value;
                    this.RaisePropertyChanged("Kaynak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Tarih {
            get {
                return this.TarihField;
            }
            set {
                if ((this.TarihField.Equals(value) != true)) {
                    this.TarihField = value;
                    this.RaisePropertyChanged("Tarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UyeId {
            get {
                return this.UyeIdField;
            }
            set {
                if ((this.UyeIdField.Equals(value) != true)) {
                    this.UyeIdField = value;
                    this.RaisePropertyChanged("UyeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UyeIzinGecmisiFiltre", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class UyeIzinGecmisiFiltre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DegerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DuzenlemeTarihBaslangicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DuzenlemeTarihBitisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Duzenleyen_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IzinTipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KaynakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UyeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Deger {
            get {
                return this.DegerField;
            }
            set {
                if ((this.DegerField.Equals(value) != true)) {
                    this.DegerField = value;
                    this.RaisePropertyChanged("Deger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DuzenlemeTarihBaslangic {
            get {
                return this.DuzenlemeTarihBaslangicField;
            }
            set {
                if ((this.DuzenlemeTarihBaslangicField.Equals(value) != true)) {
                    this.DuzenlemeTarihBaslangicField = value;
                    this.RaisePropertyChanged("DuzenlemeTarihBaslangic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DuzenlemeTarihBitis {
            get {
                return this.DuzenlemeTarihBitisField;
            }
            set {
                if ((this.DuzenlemeTarihBitisField.Equals(value) != true)) {
                    this.DuzenlemeTarihBitisField = value;
                    this.RaisePropertyChanged("DuzenlemeTarihBitis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duzenleyen_Id {
            get {
                return this.Duzenleyen_IdField;
            }
            set {
                if ((this.Duzenleyen_IdField.Equals(value) != true)) {
                    this.Duzenleyen_IdField = value;
                    this.RaisePropertyChanged("Duzenleyen_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IzinTip {
            get {
                return this.IzinTipField;
            }
            set {
                if ((this.IzinTipField.Equals(value) != true)) {
                    this.IzinTipField = value;
                    this.RaisePropertyChanged("IzinTip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kaynak {
            get {
                return this.KaynakField;
            }
            set {
                if ((object.ReferenceEquals(this.KaynakField, value) != true)) {
                    this.KaynakField = value;
                    this.RaisePropertyChanged("Kaynak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UyeId {
            get {
                return this.UyeIdField;
            }
            set {
                if ((this.UyeIdField.Equals(value) != true)) {
                    this.UyeIdField = value;
                    this.RaisePropertyChanged("UyeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UyeServis.IUyeServis")]
    public interface IUyeServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/GirisYap", ReplyAction="http://tempuri.org/IUyeServis/GirisYapResponse")]
        TicimaxWebServicesSample.UyeServis.UyeGirisiSonuc GirisYap(TicimaxWebServicesSample.UyeServis.UyeGirisi ug);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/GirisYap", ReplyAction="http://tempuri.org/IUyeServis/GirisYapResponse")]
        System.Threading.Tasks.Task<TicimaxWebServicesSample.UyeServis.UyeGirisiSonuc> GirisYapAsync(TicimaxWebServicesSample.UyeServis.UyeGirisi ug);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/SelectUyeler", ReplyAction="http://tempuri.org/IUyeServis/SelectUyelerResponse")]
        System.Collections.Generic.List<TicimaxWebServicesSample.UyeServis.Uye> SelectUyeler(string UyeKodu, TicimaxWebServicesSample.UyeServis.UyeFiltre filtre, TicimaxWebServicesSample.UyeServis.UyeSayfalama sayfalama);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/SelectUyeler", ReplyAction="http://tempuri.org/IUyeServis/SelectUyelerResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TicimaxWebServicesSample.UyeServis.Uye>> SelectUyelerAsync(string UyeKodu, TicimaxWebServicesSample.UyeServis.UyeFiltre filtre, TicimaxWebServicesSample.UyeServis.UyeSayfalama sayfalama);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/SelectUyeIdByMailOrTel", ReplyAction="http://tempuri.org/IUyeServis/SelectUyeIdByMailOrTelResponse")]
        System.Collections.Generic.List<int> SelectUyeIdByMailOrTel(string UyeKodu, string uyeMail, string tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/SelectUyeIdByMailOrTel", ReplyAction="http://tempuri.org/IUyeServis/SelectUyeIdByMailOrTelResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> SelectUyeIdByMailOrTelAsync(string UyeKodu, string uyeMail, string tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/SaveUye", ReplyAction="http://tempuri.org/IUyeServis/SaveUyeResponse")]
        int SaveUye(string UyeKodu, TicimaxWebServicesSample.UyeServis.Uye u, TicimaxWebServicesSample.UyeServis.UyeAyar ayar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/SaveUye", ReplyAction="http://tempuri.org/IUyeServis/SaveUyeResponse")]
        System.Threading.Tasks.Task<int> SaveUyeAsync(string UyeKodu, TicimaxWebServicesSample.UyeServis.Uye u, TicimaxWebServicesSample.UyeServis.UyeAyar ayar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/SelectUyeAdres", ReplyAction="http://tempuri.org/IUyeServis/SelectUyeAdresResponse")]
        System.Collections.Generic.List<TicimaxWebServicesSample.UyeServis.UyeAdres> SelectUyeAdres(string UyeKodu, int adresId, int uyeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/SelectUyeAdres", ReplyAction="http://tempuri.org/IUyeServis/SelectUyeAdresResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TicimaxWebServicesSample.UyeServis.UyeAdres>> SelectUyeAdresAsync(string UyeKodu, int adresId, int uyeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/SaveUyeAdres", ReplyAction="http://tempuri.org/IUyeServis/SaveUyeAdresResponse")]
        int SaveUyeAdres(string UyeKodu, TicimaxWebServicesSample.UyeServis.UyeAdres adres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/SaveUyeAdres", ReplyAction="http://tempuri.org/IUyeServis/SaveUyeAdresResponse")]
        System.Threading.Tasks.Task<int> SaveUyeAdresAsync(string UyeKodu, TicimaxWebServicesSample.UyeServis.UyeAdres adres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/SelectUyeTuru", ReplyAction="http://tempuri.org/IUyeServis/SelectUyeTuruResponse")]
        System.Collections.Generic.List<TicimaxWebServicesSample.UyeServis.UyeTuru> SelectUyeTuru(string UyeKodu, int uyeTuruId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/SelectUyeTuru", ReplyAction="http://tempuri.org/IUyeServis/SelectUyeTuruResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TicimaxWebServicesSample.UyeServis.UyeTuru>> SelectUyeTuruAsync(string UyeKodu, int uyeTuruId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/SaveUyeTuru", ReplyAction="http://tempuri.org/IUyeServis/SaveUyeTuruResponse")]
        int SaveUyeTuru(string UyeKodu, TicimaxWebServicesSample.UyeServis.UyeTuru u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/SaveUyeTuru", ReplyAction="http://tempuri.org/IUyeServis/SaveUyeTuruResponse")]
        System.Threading.Tasks.Task<int> SaveUyeTuruAsync(string UyeKodu, TicimaxWebServicesSample.UyeServis.UyeTuru u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/DeleteUye", ReplyAction="http://tempuri.org/IUyeServis/DeleteUyeResponse")]
        TicimaxWebServicesSample.UyeServis.UyeSilResponse DeleteUye(string UyeKodu, int uyeId, string mailAdresi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/DeleteUye", ReplyAction="http://tempuri.org/IUyeServis/DeleteUyeResponse")]
        System.Threading.Tasks.Task<TicimaxWebServicesSample.UyeServis.UyeSilResponse> DeleteUyeAsync(string UyeKodu, int uyeId, string mailAdresi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/SelectUyeIzinGecmisi", ReplyAction="http://tempuri.org/IUyeServis/SelectUyeIzinGecmisiResponse")]
        TicimaxWebServicesSample.UyeServis.UyeIzinGecmisiResponse SelectUyeIzinGecmisi(string UyeKodu, TicimaxWebServicesSample.UyeServis.UyeIzinGecmisiFiltre filtre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUyeServis/SelectUyeIzinGecmisi", ReplyAction="http://tempuri.org/IUyeServis/SelectUyeIzinGecmisiResponse")]
        System.Threading.Tasks.Task<TicimaxWebServicesSample.UyeServis.UyeIzinGecmisiResponse> SelectUyeIzinGecmisiAsync(string UyeKodu, TicimaxWebServicesSample.UyeServis.UyeIzinGecmisiFiltre filtre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUyeServisChannel : TicimaxWebServicesSample.UyeServis.IUyeServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UyeServisClient : System.ServiceModel.ClientBase<TicimaxWebServicesSample.UyeServis.IUyeServis>, TicimaxWebServicesSample.UyeServis.IUyeServis {
        
        public UyeServisClient() {
        }
        
        public UyeServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UyeServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UyeServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UyeServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TicimaxWebServicesSample.UyeServis.UyeGirisiSonuc GirisYap(TicimaxWebServicesSample.UyeServis.UyeGirisi ug) {
            return base.Channel.GirisYap(ug);
        }
        
        public System.Threading.Tasks.Task<TicimaxWebServicesSample.UyeServis.UyeGirisiSonuc> GirisYapAsync(TicimaxWebServicesSample.UyeServis.UyeGirisi ug) {
            return base.Channel.GirisYapAsync(ug);
        }
        
        public System.Collections.Generic.List<TicimaxWebServicesSample.UyeServis.Uye> SelectUyeler(string UyeKodu, TicimaxWebServicesSample.UyeServis.UyeFiltre filtre, TicimaxWebServicesSample.UyeServis.UyeSayfalama sayfalama) {
            return base.Channel.SelectUyeler(UyeKodu, filtre, sayfalama);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TicimaxWebServicesSample.UyeServis.Uye>> SelectUyelerAsync(string UyeKodu, TicimaxWebServicesSample.UyeServis.UyeFiltre filtre, TicimaxWebServicesSample.UyeServis.UyeSayfalama sayfalama) {
            return base.Channel.SelectUyelerAsync(UyeKodu, filtre, sayfalama);
        }
        
        public System.Collections.Generic.List<int> SelectUyeIdByMailOrTel(string UyeKodu, string uyeMail, string tel) {
            return base.Channel.SelectUyeIdByMailOrTel(UyeKodu, uyeMail, tel);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> SelectUyeIdByMailOrTelAsync(string UyeKodu, string uyeMail, string tel) {
            return base.Channel.SelectUyeIdByMailOrTelAsync(UyeKodu, uyeMail, tel);
        }
        
        public int SaveUye(string UyeKodu, TicimaxWebServicesSample.UyeServis.Uye u, TicimaxWebServicesSample.UyeServis.UyeAyar ayar) {
            return base.Channel.SaveUye(UyeKodu, u, ayar);
        }
        
        public System.Threading.Tasks.Task<int> SaveUyeAsync(string UyeKodu, TicimaxWebServicesSample.UyeServis.Uye u, TicimaxWebServicesSample.UyeServis.UyeAyar ayar) {
            return base.Channel.SaveUyeAsync(UyeKodu, u, ayar);
        }
        
        public System.Collections.Generic.List<TicimaxWebServicesSample.UyeServis.UyeAdres> SelectUyeAdres(string UyeKodu, int adresId, int uyeId) {
            return base.Channel.SelectUyeAdres(UyeKodu, adresId, uyeId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TicimaxWebServicesSample.UyeServis.UyeAdres>> SelectUyeAdresAsync(string UyeKodu, int adresId, int uyeId) {
            return base.Channel.SelectUyeAdresAsync(UyeKodu, adresId, uyeId);
        }
        
        public int SaveUyeAdres(string UyeKodu, TicimaxWebServicesSample.UyeServis.UyeAdres adres) {
            return base.Channel.SaveUyeAdres(UyeKodu, adres);
        }
        
        public System.Threading.Tasks.Task<int> SaveUyeAdresAsync(string UyeKodu, TicimaxWebServicesSample.UyeServis.UyeAdres adres) {
            return base.Channel.SaveUyeAdresAsync(UyeKodu, adres);
        }
        
        public System.Collections.Generic.List<TicimaxWebServicesSample.UyeServis.UyeTuru> SelectUyeTuru(string UyeKodu, int uyeTuruId) {
            return base.Channel.SelectUyeTuru(UyeKodu, uyeTuruId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TicimaxWebServicesSample.UyeServis.UyeTuru>> SelectUyeTuruAsync(string UyeKodu, int uyeTuruId) {
            return base.Channel.SelectUyeTuruAsync(UyeKodu, uyeTuruId);
        }
        
        public int SaveUyeTuru(string UyeKodu, TicimaxWebServicesSample.UyeServis.UyeTuru u) {
            return base.Channel.SaveUyeTuru(UyeKodu, u);
        }
        
        public System.Threading.Tasks.Task<int> SaveUyeTuruAsync(string UyeKodu, TicimaxWebServicesSample.UyeServis.UyeTuru u) {
            return base.Channel.SaveUyeTuruAsync(UyeKodu, u);
        }
        
        public TicimaxWebServicesSample.UyeServis.UyeSilResponse DeleteUye(string UyeKodu, int uyeId, string mailAdresi) {
            return base.Channel.DeleteUye(UyeKodu, uyeId, mailAdresi);
        }
        
        public System.Threading.Tasks.Task<TicimaxWebServicesSample.UyeServis.UyeSilResponse> DeleteUyeAsync(string UyeKodu, int uyeId, string mailAdresi) {
            return base.Channel.DeleteUyeAsync(UyeKodu, uyeId, mailAdresi);
        }
        
        public TicimaxWebServicesSample.UyeServis.UyeIzinGecmisiResponse SelectUyeIzinGecmisi(string UyeKodu, TicimaxWebServicesSample.UyeServis.UyeIzinGecmisiFiltre filtre) {
            return base.Channel.SelectUyeIzinGecmisi(UyeKodu, filtre);
        }
        
        public System.Threading.Tasks.Task<TicimaxWebServicesSample.UyeServis.UyeIzinGecmisiResponse> SelectUyeIzinGecmisiAsync(string UyeKodu, TicimaxWebServicesSample.UyeServis.UyeIzinGecmisiFiltre filtre) {
            return base.Channel.SelectUyeIzinGecmisiAsync(UyeKodu, filtre);
        }
    }
}
